"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.sequelize = void 0;
const sequelize_1 = require("sequelize");
const config_1 = require("../config/config");
const users_1 = __importDefault(require("./users"));
const posts_1 = __importDefault(require("./posts"));
const comments_1 = __importDefault(require("./comments"));
const like_1 = __importDefault(require("./like"));
const env = process.env.NODE_ENV || "development";
// const config = config;
exports.sequelize = new sequelize_1.Sequelize(config_1.config.development.database, config_1.config.development.username, config_1.config.development.password, { host: config_1.config.development.host, dialect: config_1.config.development.dialect });
users_1.default.initiate(exports.sequelize);
posts_1.default.initiate(exports.sequelize);
comments_1.default.initiate(exports.sequelize);
like_1.default.initiate(exports.sequelize);
users_1.default.associate();
posts_1.default.associate();
comments_1.default.associate();
like_1.default.associate();
exports.default = { Users: users_1.default, Posts: posts_1.default, Comments: comments_1.default, Like: like_1.default };
